export const PLAYER_KEY        = 'kwest:player'
export const SESSIONS_KEY      = 'kwest:sessions'
export const ACTIVE_KEY        = 'kwest:active-session'
export const RECENTS_KEY       = 'kwest:recent-exercises'
export const REST_DURATION_KEY = 'kwest:rest-duration'
export const REST_TIMER_KEY    = 'kwest:rest-timer'      // minuteur de repos en cours
export const ROUTINES_KEY      = 'kwest:routines'
export const DELETED_KEY       = 'kwest:deleted-sessions' // tombstones : suppressions cloud à rejouer
export const DELETED_ROUTINES_KEY = 'kwest:deleted-routines'
export const PENDING_KEY       = 'kwest:pending'          // envois pas encore confirmés par le cloud
export const OWNER_KEY         = 'kwest:owner'            // compte auquel appartiennent les données locales
